# This file was generated by GoReleaser. DO NOT EDIT.
cask "aibox" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "4cdce4b046eaf279255ae46c1a8451d92aeb5d1b84252d94afa38f4b8b26a8ed"
      url "https://github.com/The127/aibox/releases/download/v#{version}/aibox_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "aibox"
  desc "Run Claude Code inside a microVM, with your project folder mounted into it."
  homepage "https://github.com/The127/aibox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aibox"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aibox"]
    end
  end

  # No zap stanza required
end
