# This file was generated by GoReleaser. DO NOT EDIT.
cask "aibox" do
  version "1.3.0"

  on_macos do
    on_arm do
      sha256 "3f2f9ead6ec246739646d01946eaf94be9533f7745ffc2c42ae22567d4afa84e"
      url "https://github.com/The127/aibox/releases/download/v#{version}/aibox_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "aibox"
  desc "Run Claude Code inside a microVM, with your project folder mounted into it."
  homepage "https://github.com/The127/aibox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aibox"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aibox"]
    end
  end

  # No zap stanza required
end
