# This file was generated by GoReleaser. DO NOT EDIT.
cask "aibox" do
  version "1.1.0"

  on_macos do
    on_arm do
      sha256 "66cdead48dbbb5bdc1a81b429a4c5c8c3442eaea6e4efa00cd5b3ca0a3d5aae2"
      url "https://github.com/The127/aibox/releases/download/v#{version}/aibox_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "aibox"
  desc "Run Claude Code inside a microVM, with your project folder mounted into it."
  homepage "https://github.com/The127/aibox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aibox"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aibox"]
    end
  end

  # No zap stanza required
end
